package com.hzhx.greenFinance.entity;

public class AcceptanceBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businesstypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.billNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.acceptanceNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String acceptanceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.billAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String billamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String issuedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String expiringdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.paymentDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String paymentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.payingBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String payingbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.payeeName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String payeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.payeeBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String payeebankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String fivelevelcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String guaranteemethodcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String marginlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String greendecideddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String cbrcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String isenvironmentalinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String environmentalinterestcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_acceptance_bill_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.organization
     *
     * @return the value of send_green_thr_acceptance_bill_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.organization
     *
     * @param organization the value for send_green_thr_acceptance_bill_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.businessTypeCd
     *
     * @return the value of send_green_thr_acceptance_bill_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinesstypecd() {
        return businesstypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.businessTypeCd
     *
     * @param businesstypecd the value for send_green_thr_acceptance_bill_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinesstypecd(String businesstypecd) {
        this.businesstypecd = businesstypecd == null ? null : businesstypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.businessDate
     *
     * @return the value of send_green_thr_acceptance_bill_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.businessDate
     *
     * @param businessdate the value for send_green_thr_acceptance_bill_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.billNo
     *
     * @return the value of send_green_thr_acceptance_bill_info.billNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.billNo
     *
     * @param billno the value for send_green_thr_acceptance_bill_info.billNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.acceptanceNo
     *
     * @return the value of send_green_thr_acceptance_bill_info.acceptanceNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getAcceptanceno() {
        return acceptanceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.acceptanceNo
     *
     * @param acceptanceno the value for send_green_thr_acceptance_bill_info.acceptanceNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setAcceptanceno(String acceptanceno) {
        this.acceptanceno = acceptanceno == null ? null : acceptanceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.businessOrg
     *
     * @return the value of send_green_thr_acceptance_bill_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessorg() {
        return businessorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.businessOrg
     *
     * @param businessorg the value for send_green_thr_acceptance_bill_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessorg(String businessorg) {
        this.businessorg = businessorg == null ? null : businessorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.customerNo
     *
     * @return the value of send_green_thr_acceptance_bill_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.customerNo
     *
     * @param customerno the value for send_green_thr_acceptance_bill_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.billAmount
     *
     * @return the value of send_green_thr_acceptance_bill_info.billAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.billAmount
     *
     * @param billamount the value for send_green_thr_acceptance_bill_info.billAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBillamount(String billamount) {
        this.billamount = billamount == null ? null : billamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.issueDate
     *
     * @return the value of send_green_thr_acceptance_bill_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIssuedate() {
        return issuedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.issueDate
     *
     * @param issuedate the value for send_green_thr_acceptance_bill_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIssuedate(String issuedate) {
        this.issuedate = issuedate == null ? null : issuedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.expiringDate
     *
     * @return the value of send_green_thr_acceptance_bill_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getExpiringdate() {
        return expiringdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.expiringDate
     *
     * @param expiringdate the value for send_green_thr_acceptance_bill_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setExpiringdate(String expiringdate) {
        this.expiringdate = expiringdate == null ? null : expiringdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.paymentDate
     *
     * @return the value of send_green_thr_acceptance_bill_info.paymentDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.paymentDate
     *
     * @param paymentdate the value for send_green_thr_acceptance_bill_info.paymentDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPaymentdate(String paymentdate) {
        this.paymentdate = paymentdate == null ? null : paymentdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.payingBankName
     *
     * @return the value of send_green_thr_acceptance_bill_info.payingBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPayingbankname() {
        return payingbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.payingBankName
     *
     * @param payingbankname the value for send_green_thr_acceptance_bill_info.payingBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPayingbankname(String payingbankname) {
        this.payingbankname = payingbankname == null ? null : payingbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.payeeName
     *
     * @return the value of send_green_thr_acceptance_bill_info.payeeName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPayeename() {
        return payeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.payeeName
     *
     * @param payeename the value for send_green_thr_acceptance_bill_info.payeeName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPayeename(String payeename) {
        this.payeename = payeename == null ? null : payeename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.payeeBankName
     *
     * @return the value of send_green_thr_acceptance_bill_info.payeeBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPayeebankname() {
        return payeebankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.payeeBankName
     *
     * @param payeebankname the value for send_green_thr_acceptance_bill_info.payeeBankName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPayeebankname(String payeebankname) {
        this.payeebankname = payeebankname == null ? null : payeebankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.fiveLevelCd
     *
     * @return the value of send_green_thr_acceptance_bill_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getFivelevelcd() {
        return fivelevelcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.fiveLevelCd
     *
     * @param fivelevelcd the value for send_green_thr_acceptance_bill_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setFivelevelcd(String fivelevelcd) {
        this.fivelevelcd = fivelevelcd == null ? null : fivelevelcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.guaranteeMethodCd
     *
     * @return the value of send_green_thr_acceptance_bill_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGuaranteemethodcd() {
        return guaranteemethodcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.guaranteeMethodCd
     *
     * @param guaranteemethodcd the value for send_green_thr_acceptance_bill_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGuaranteemethodcd(String guaranteemethodcd) {
        this.guaranteemethodcd = guaranteemethodcd == null ? null : guaranteemethodcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.marginLevel
     *
     * @return the value of send_green_thr_acceptance_bill_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getMarginlevel() {
        return marginlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.marginLevel
     *
     * @param marginlevel the value for send_green_thr_acceptance_bill_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setMarginlevel(String marginlevel) {
        this.marginlevel = marginlevel == null ? null : marginlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.greenDecidedDate
     *
     * @return the value of send_green_thr_acceptance_bill_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGreendecideddate() {
        return greendecideddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.greenDecidedDate
     *
     * @param greendecideddate the value for send_green_thr_acceptance_bill_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGreendecideddate(String greendecideddate) {
        this.greendecideddate = greendecideddate == null ? null : greendecideddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.cbrcGreenClass
     *
     * @return the value of send_green_thr_acceptance_bill_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCbrcgreenclass() {
        return cbrcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.cbrcGreenClass
     *
     * @param cbrcgreenclass the value for send_green_thr_acceptance_bill_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCbrcgreenclass(String cbrcgreenclass) {
        this.cbrcgreenclass = cbrcgreenclass == null ? null : cbrcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.isEnvironmentalInterest
     *
     * @return the value of send_green_thr_acceptance_bill_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIsenvironmentalinterest() {
        return isenvironmentalinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.isEnvironmentalInterest
     *
     * @param isenvironmentalinterest the value for send_green_thr_acceptance_bill_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIsenvironmentalinterest(String isenvironmentalinterest) {
        this.isenvironmentalinterest = isenvironmentalinterest == null ? null : isenvironmentalinterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.environmentalInterestCd
     *
     * @return the value of send_green_thr_acceptance_bill_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnvironmentalinterestcd() {
        return environmentalinterestcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.environmentalInterestCd
     *
     * @param environmentalinterestcd the value for send_green_thr_acceptance_bill_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnvironmentalinterestcd(String environmentalinterestcd) {
        this.environmentalinterestcd = environmentalinterestcd == null ? null : environmentalinterestcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_acceptance_bill_info.gdate
     *
     * @return the value of send_green_thr_acceptance_bill_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_acceptance_bill_info.gdate
     *
     * @param gdate the value for send_green_thr_acceptance_bill_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}