package com.hzhx.greenFinance.entity;

import java.math.BigDecimal;

public class BondInvestment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.organization
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.businessTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String businesstypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.businessDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.tradeNo
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String tradeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.businessOrg
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String businessorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.bondTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String bondtypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.bondCode
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String bondcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.bondName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String bondname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.parValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private BigDecimal parvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.couponRate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private BigDecimal couponrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.issueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String issuedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.expiringDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String expiringdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.repaymentMethodCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String repaymentmethodcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.timeLimit
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private Integer timelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.creditRating
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String creditrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.creditRatingAgency
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String creditratingagency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.issuerName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String issuername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.issuerCountryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String issuercountrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.issuerIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String issuerindustrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.bondIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String bondindustrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.tradeValueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String tradevaluedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.fiveLevelCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String fivelevelcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.remainingParValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private BigDecimal remainingparvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.businessBalance
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private BigDecimal businessbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.defaultAmount
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private BigDecimal defaultamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.greenDecidedDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String greendecideddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.cbrcGreenClass
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String cbrcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.isEnvironmentalInterest
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String isenvironmentalinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.environmentalInterestCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String environmentalinterestcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.isConstructionBond
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String isconstructionbond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_bond_investment_info.gdate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.organization
     *
     * @return the value of send_green_thr_bond_investment_info.organization
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.organization
     *
     * @param organization the value for send_green_thr_bond_investment_info.organization
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.businessTypeCd
     *
     * @return the value of send_green_thr_bond_investment_info.businessTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBusinesstypecd() {
        return businesstypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.businessTypeCd
     *
     * @param businesstypecd the value for send_green_thr_bond_investment_info.businessTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBusinesstypecd(String businesstypecd) {
        this.businesstypecd = businesstypecd == null ? null : businesstypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.businessDate
     *
     * @return the value of send_green_thr_bond_investment_info.businessDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.businessDate
     *
     * @param businessdate the value for send_green_thr_bond_investment_info.businessDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.tradeNo
     *
     * @return the value of send_green_thr_bond_investment_info.tradeNo
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.tradeNo
     *
     * @param tradeno the value for send_green_thr_bond_investment_info.tradeNo
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno == null ? null : tradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.businessOrg
     *
     * @return the value of send_green_thr_bond_investment_info.businessOrg
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBusinessorg() {
        return businessorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.businessOrg
     *
     * @param businessorg the value for send_green_thr_bond_investment_info.businessOrg
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBusinessorg(String businessorg) {
        this.businessorg = businessorg == null ? null : businessorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.bondTypeCd
     *
     * @return the value of send_green_thr_bond_investment_info.bondTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBondtypecd() {
        return bondtypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.bondTypeCd
     *
     * @param bondtypecd the value for send_green_thr_bond_investment_info.bondTypeCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBondtypecd(String bondtypecd) {
        this.bondtypecd = bondtypecd == null ? null : bondtypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.bondCode
     *
     * @return the value of send_green_thr_bond_investment_info.bondCode
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBondcode() {
        return bondcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.bondCode
     *
     * @param bondcode the value for send_green_thr_bond_investment_info.bondCode
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBondcode(String bondcode) {
        this.bondcode = bondcode == null ? null : bondcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.bondName
     *
     * @return the value of send_green_thr_bond_investment_info.bondName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBondname() {
        return bondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.bondName
     *
     * @param bondname the value for send_green_thr_bond_investment_info.bondName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBondname(String bondname) {
        this.bondname = bondname == null ? null : bondname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.parValue
     *
     * @return the value of send_green_thr_bond_investment_info.parValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public BigDecimal getParvalue() {
        return parvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.parValue
     *
     * @param parvalue the value for send_green_thr_bond_investment_info.parValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setParvalue(BigDecimal parvalue) {
        this.parvalue = parvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.couponRate
     *
     * @return the value of send_green_thr_bond_investment_info.couponRate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public BigDecimal getCouponrate() {
        return couponrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.couponRate
     *
     * @param couponrate the value for send_green_thr_bond_investment_info.couponRate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setCouponrate(BigDecimal couponrate) {
        this.couponrate = couponrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.issueDate
     *
     * @return the value of send_green_thr_bond_investment_info.issueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIssuedate() {
        return issuedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.issueDate
     *
     * @param issuedate the value for send_green_thr_bond_investment_info.issueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIssuedate(String issuedate) {
        this.issuedate = issuedate == null ? null : issuedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.expiringDate
     *
     * @return the value of send_green_thr_bond_investment_info.expiringDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getExpiringdate() {
        return expiringdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.expiringDate
     *
     * @param expiringdate the value for send_green_thr_bond_investment_info.expiringDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setExpiringdate(String expiringdate) {
        this.expiringdate = expiringdate == null ? null : expiringdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.repaymentMethodCd
     *
     * @return the value of send_green_thr_bond_investment_info.repaymentMethodCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getRepaymentmethodcd() {
        return repaymentmethodcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.repaymentMethodCd
     *
     * @param repaymentmethodcd the value for send_green_thr_bond_investment_info.repaymentMethodCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setRepaymentmethodcd(String repaymentmethodcd) {
        this.repaymentmethodcd = repaymentmethodcd == null ? null : repaymentmethodcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.timeLimit
     *
     * @return the value of send_green_thr_bond_investment_info.timeLimit
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public Integer getTimelimit() {
        return timelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.timeLimit
     *
     * @param timelimit the value for send_green_thr_bond_investment_info.timeLimit
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setTimelimit(Integer timelimit) {
        this.timelimit = timelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.creditRating
     *
     * @return the value of send_green_thr_bond_investment_info.creditRating
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getCreditrating() {
        return creditrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.creditRating
     *
     * @param creditrating the value for send_green_thr_bond_investment_info.creditRating
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setCreditrating(String creditrating) {
        this.creditrating = creditrating == null ? null : creditrating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.creditRatingAgency
     *
     * @return the value of send_green_thr_bond_investment_info.creditRatingAgency
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getCreditratingagency() {
        return creditratingagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.creditRatingAgency
     *
     * @param creditratingagency the value for send_green_thr_bond_investment_info.creditRatingAgency
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setCreditratingagency(String creditratingagency) {
        this.creditratingagency = creditratingagency == null ? null : creditratingagency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.issuerName
     *
     * @return the value of send_green_thr_bond_investment_info.issuerName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIssuername() {
        return issuername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.issuerName
     *
     * @param issuername the value for send_green_thr_bond_investment_info.issuerName
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIssuername(String issuername) {
        this.issuername = issuername == null ? null : issuername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.issuerCountryCd
     *
     * @return the value of send_green_thr_bond_investment_info.issuerCountryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIssuercountrycd() {
        return issuercountrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.issuerCountryCd
     *
     * @param issuercountrycd the value for send_green_thr_bond_investment_info.issuerCountryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIssuercountrycd(String issuercountrycd) {
        this.issuercountrycd = issuercountrycd == null ? null : issuercountrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.issuerIndustryCd
     *
     * @return the value of send_green_thr_bond_investment_info.issuerIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIssuerindustrycd() {
        return issuerindustrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.issuerIndustryCd
     *
     * @param issuerindustrycd the value for send_green_thr_bond_investment_info.issuerIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIssuerindustrycd(String issuerindustrycd) {
        this.issuerindustrycd = issuerindustrycd == null ? null : issuerindustrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.bondIndustryCd
     *
     * @return the value of send_green_thr_bond_investment_info.bondIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getBondindustrycd() {
        return bondindustrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.bondIndustryCd
     *
     * @param bondindustrycd the value for send_green_thr_bond_investment_info.bondIndustryCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBondindustrycd(String bondindustrycd) {
        this.bondindustrycd = bondindustrycd == null ? null : bondindustrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.tradeValueDate
     *
     * @return the value of send_green_thr_bond_investment_info.tradeValueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getTradevaluedate() {
        return tradevaluedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.tradeValueDate
     *
     * @param tradevaluedate the value for send_green_thr_bond_investment_info.tradeValueDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setTradevaluedate(String tradevaluedate) {
        this.tradevaluedate = tradevaluedate == null ? null : tradevaluedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.fiveLevelCd
     *
     * @return the value of send_green_thr_bond_investment_info.fiveLevelCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getFivelevelcd() {
        return fivelevelcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.fiveLevelCd
     *
     * @param fivelevelcd the value for send_green_thr_bond_investment_info.fiveLevelCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setFivelevelcd(String fivelevelcd) {
        this.fivelevelcd = fivelevelcd == null ? null : fivelevelcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.remainingParValue
     *
     * @return the value of send_green_thr_bond_investment_info.remainingParValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public BigDecimal getRemainingparvalue() {
        return remainingparvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.remainingParValue
     *
     * @param remainingparvalue the value for send_green_thr_bond_investment_info.remainingParValue
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setRemainingparvalue(BigDecimal remainingparvalue) {
        this.remainingparvalue = remainingparvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.businessBalance
     *
     * @return the value of send_green_thr_bond_investment_info.businessBalance
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public BigDecimal getBusinessbalance() {
        return businessbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.businessBalance
     *
     * @param businessbalance the value for send_green_thr_bond_investment_info.businessBalance
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setBusinessbalance(BigDecimal businessbalance) {
        this.businessbalance = businessbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.defaultAmount
     *
     * @return the value of send_green_thr_bond_investment_info.defaultAmount
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public BigDecimal getDefaultamount() {
        return defaultamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.defaultAmount
     *
     * @param defaultamount the value for send_green_thr_bond_investment_info.defaultAmount
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setDefaultamount(BigDecimal defaultamount) {
        this.defaultamount = defaultamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.greenDecidedDate
     *
     * @return the value of send_green_thr_bond_investment_info.greenDecidedDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getGreendecideddate() {
        return greendecideddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.greenDecidedDate
     *
     * @param greendecideddate the value for send_green_thr_bond_investment_info.greenDecidedDate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setGreendecideddate(String greendecideddate) {
        this.greendecideddate = greendecideddate == null ? null : greendecideddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.cbrcGreenClass
     *
     * @return the value of send_green_thr_bond_investment_info.cbrcGreenClass
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getCbrcgreenclass() {
        return cbrcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.cbrcGreenClass
     *
     * @param cbrcgreenclass the value for send_green_thr_bond_investment_info.cbrcGreenClass
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setCbrcgreenclass(String cbrcgreenclass) {
        this.cbrcgreenclass = cbrcgreenclass == null ? null : cbrcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.isEnvironmentalInterest
     *
     * @return the value of send_green_thr_bond_investment_info.isEnvironmentalInterest
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIsenvironmentalinterest() {
        return isenvironmentalinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.isEnvironmentalInterest
     *
     * @param isenvironmentalinterest the value for send_green_thr_bond_investment_info.isEnvironmentalInterest
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIsenvironmentalinterest(String isenvironmentalinterest) {
        this.isenvironmentalinterest = isenvironmentalinterest == null ? null : isenvironmentalinterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.environmentalInterestCd
     *
     * @return the value of send_green_thr_bond_investment_info.environmentalInterestCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getEnvironmentalinterestcd() {
        return environmentalinterestcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.environmentalInterestCd
     *
     * @param environmentalinterestcd the value for send_green_thr_bond_investment_info.environmentalInterestCd
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setEnvironmentalinterestcd(String environmentalinterestcd) {
        this.environmentalinterestcd = environmentalinterestcd == null ? null : environmentalinterestcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.isConstructionBond
     *
     * @return the value of send_green_thr_bond_investment_info.isConstructionBond
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getIsconstructionbond() {
        return isconstructionbond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.isConstructionBond
     *
     * @param isconstructionbond the value for send_green_thr_bond_investment_info.isConstructionBond
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setIsconstructionbond(String isconstructionbond) {
        this.isconstructionbond = isconstructionbond == null ? null : isconstructionbond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_bond_investment_info.gdate
     *
     * @return the value of send_green_thr_bond_investment_info.gdate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_bond_investment_info.gdate
     *
     * @param gdate the value for send_green_thr_bond_investment_info.gdate
     *
     * @mbggenerated Mon Nov 23 14:46:45 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}