package com.hzhx.greenFinance.entity;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.enterpriseName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String enterprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.unifiedSocialCreditCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String unifiedsocialcreditcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.legalPerson
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String legalperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.registeredAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String registeredamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.registeredAreaCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String registeredareacd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String industrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.ownershipTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String ownershiptypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.scaleTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String scaletypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.businessScope
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String majorbusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.unifiedCreditFlag
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String unifiedcreditflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.creditLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String creditlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_comapny_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.organization
     *
     * @return the value of send_green_thr_comapny_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.organization
     *
     * @param organization the value for send_green_thr_comapny_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.customerNo
     *
     * @return the value of send_green_thr_comapny_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.customerNo
     *
     * @param customerno the value for send_green_thr_comapny_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.enterpriseName
     *
     * @return the value of send_green_thr_comapny_info.enterpriseName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.enterpriseName
     *
     * @param enterprisename the value for send_green_thr_comapny_info.enterpriseName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename == null ? null : enterprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.unifiedSocialCreditCd
     *
     * @return the value of send_green_thr_comapny_info.unifiedSocialCreditCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getUnifiedsocialcreditcd() {
        return unifiedsocialcreditcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.unifiedSocialCreditCd
     *
     * @param unifiedsocialcreditcd the value for send_green_thr_comapny_info.unifiedSocialCreditCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setUnifiedsocialcreditcd(String unifiedsocialcreditcd) {
        this.unifiedsocialcreditcd = unifiedsocialcreditcd == null ? null : unifiedsocialcreditcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.legalPerson
     *
     * @return the value of send_green_thr_comapny_info.legalPerson
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLegalperson() {
        return legalperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.legalPerson
     *
     * @param legalperson the value for send_green_thr_comapny_info.legalPerson
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson == null ? null : legalperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.registeredAmount
     *
     * @return the value of send_green_thr_comapny_info.registeredAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getRegisteredamount() {
        return registeredamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.registeredAmount
     *
     * @param registeredamount the value for send_green_thr_comapny_info.registeredAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setRegisteredamount(String registeredamount) {
        this.registeredamount = registeredamount == null ? null : registeredamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.registeredAreaCd
     *
     * @return the value of send_green_thr_comapny_info.registeredAreaCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getRegisteredareacd() {
        return registeredareacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.registeredAreaCd
     *
     * @param registeredareacd the value for send_green_thr_comapny_info.registeredAreaCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setRegisteredareacd(String registeredareacd) {
        this.registeredareacd = registeredareacd == null ? null : registeredareacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.industryCd
     *
     * @return the value of send_green_thr_comapny_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIndustrycd() {
        return industrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.industryCd
     *
     * @param industrycd the value for send_green_thr_comapny_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIndustrycd(String industrycd) {
        this.industrycd = industrycd == null ? null : industrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.ownershipTypeCd
     *
     * @return the value of send_green_thr_comapny_info.ownershipTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOwnershiptypecd() {
        return ownershiptypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.ownershipTypeCd
     *
     * @param ownershiptypecd the value for send_green_thr_comapny_info.ownershipTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOwnershiptypecd(String ownershiptypecd) {
        this.ownershiptypecd = ownershiptypecd == null ? null : ownershiptypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.scaleTypeCd
     *
     * @return the value of send_green_thr_comapny_info.scaleTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getScaletypecd() {
        return scaletypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.scaleTypeCd
     *
     * @param scaletypecd the value for send_green_thr_comapny_info.scaleTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setScaletypecd(String scaletypecd) {
        this.scaletypecd = scaletypecd == null ? null : scaletypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.businessScope
     *
     * @return the value of send_green_thr_comapny_info.businessScope
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessscope() {
        return businessscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.businessScope
     *
     * @param businessscope the value for send_green_thr_comapny_info.businessScope
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessscope(String businessscope) {
        this.businessscope = businessscope == null ? null : businessscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.majorBusiness
     *
     * @return the value of send_green_thr_comapny_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getMajorbusiness() {
        return majorbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.majorBusiness
     *
     * @param majorbusiness the value for send_green_thr_comapny_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setMajorbusiness(String majorbusiness) {
        this.majorbusiness = majorbusiness == null ? null : majorbusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.unifiedCreditFlag
     *
     * @return the value of send_green_thr_comapny_info.unifiedCreditFlag
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getUnifiedcreditflag() {
        return unifiedcreditflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.unifiedCreditFlag
     *
     * @param unifiedcreditflag the value for send_green_thr_comapny_info.unifiedCreditFlag
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setUnifiedcreditflag(String unifiedcreditflag) {
        this.unifiedcreditflag = unifiedcreditflag == null ? null : unifiedcreditflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.creditLimit
     *
     * @return the value of send_green_thr_comapny_info.creditLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCreditlimit() {
        return creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.creditLimit
     *
     * @param creditlimit the value for send_green_thr_comapny_info.creditLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCreditlimit(String creditlimit) {
        this.creditlimit = creditlimit == null ? null : creditlimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.businessDate
     *
     * @return the value of send_green_thr_comapny_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.businessDate
     *
     * @param businessdate the value for send_green_thr_comapny_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_comapny_info.gdate
     *
     * @return the value of send_green_thr_comapny_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_comapny_info.gdate
     *
     * @param gdate the value for send_green_thr_comapny_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}