package com.hzhx.greenFinance.entity;

public class CreditInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businesstypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.letterCreditNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String lettercreditno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.letterCreditAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String lettercreditamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.letterCreditBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String lettercreditbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String issuedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String expiringdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.closeDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String closedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.revocationDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String revocationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.termTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String termtypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String fivelevelcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String guaranteemethodcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String marginlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String greendecideddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String cbrcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String isenvironmentalinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String environmentalinterestcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_credit_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.organization
     *
     * @return the value of send_green_thr_credit_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.organization
     *
     * @param organization the value for send_green_thr_credit_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.businessTypeCd
     *
     * @return the value of send_green_thr_credit_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinesstypecd() {
        return businesstypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.businessTypeCd
     *
     * @param businesstypecd the value for send_green_thr_credit_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinesstypecd(String businesstypecd) {
        this.businesstypecd = businesstypecd == null ? null : businesstypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.businessDate
     *
     * @return the value of send_green_thr_credit_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.businessDate
     *
     * @param businessdate the value for send_green_thr_credit_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.letterCreditNo
     *
     * @return the value of send_green_thr_credit_info.letterCreditNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLettercreditno() {
        return lettercreditno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.letterCreditNo
     *
     * @param lettercreditno the value for send_green_thr_credit_info.letterCreditNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLettercreditno(String lettercreditno) {
        this.lettercreditno = lettercreditno == null ? null : lettercreditno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.contractNo
     *
     * @return the value of send_green_thr_credit_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.contractNo
     *
     * @param contractno the value for send_green_thr_credit_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.businessOrg
     *
     * @return the value of send_green_thr_credit_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessorg() {
        return businessorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.businessOrg
     *
     * @param businessorg the value for send_green_thr_credit_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessorg(String businessorg) {
        this.businessorg = businessorg == null ? null : businessorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.customerNo
     *
     * @return the value of send_green_thr_credit_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.customerNo
     *
     * @param customerno the value for send_green_thr_credit_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.letterCreditAmount
     *
     * @return the value of send_green_thr_credit_info.letterCreditAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLettercreditamount() {
        return lettercreditamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.letterCreditAmount
     *
     * @param lettercreditamount the value for send_green_thr_credit_info.letterCreditAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLettercreditamount(String lettercreditamount) {
        this.lettercreditamount = lettercreditamount == null ? null : lettercreditamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.letterCreditBalance
     *
     * @return the value of send_green_thr_credit_info.letterCreditBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLettercreditbalance() {
        return lettercreditbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.letterCreditBalance
     *
     * @param lettercreditbalance the value for send_green_thr_credit_info.letterCreditBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLettercreditbalance(String lettercreditbalance) {
        this.lettercreditbalance = lettercreditbalance == null ? null : lettercreditbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.issueDate
     *
     * @return the value of send_green_thr_credit_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIssuedate() {
        return issuedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.issueDate
     *
     * @param issuedate the value for send_green_thr_credit_info.issueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIssuedate(String issuedate) {
        this.issuedate = issuedate == null ? null : issuedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.expiringDate
     *
     * @return the value of send_green_thr_credit_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getExpiringdate() {
        return expiringdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.expiringDate
     *
     * @param expiringdate the value for send_green_thr_credit_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setExpiringdate(String expiringdate) {
        this.expiringdate = expiringdate == null ? null : expiringdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.closeDate
     *
     * @return the value of send_green_thr_credit_info.closeDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getClosedate() {
        return closedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.closeDate
     *
     * @param closedate the value for send_green_thr_credit_info.closeDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setClosedate(String closedate) {
        this.closedate = closedate == null ? null : closedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.revocationDate
     *
     * @return the value of send_green_thr_credit_info.revocationDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getRevocationdate() {
        return revocationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.revocationDate
     *
     * @param revocationdate the value for send_green_thr_credit_info.revocationDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setRevocationdate(String revocationdate) {
        this.revocationdate = revocationdate == null ? null : revocationdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.termTypeCd
     *
     * @return the value of send_green_thr_credit_info.termTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getTermtypecd() {
        return termtypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.termTypeCd
     *
     * @param termtypecd the value for send_green_thr_credit_info.termTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setTermtypecd(String termtypecd) {
        this.termtypecd = termtypecd == null ? null : termtypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.fiveLevelCd
     *
     * @return the value of send_green_thr_credit_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getFivelevelcd() {
        return fivelevelcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.fiveLevelCd
     *
     * @param fivelevelcd the value for send_green_thr_credit_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setFivelevelcd(String fivelevelcd) {
        this.fivelevelcd = fivelevelcd == null ? null : fivelevelcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.guaranteeMethodCd
     *
     * @return the value of send_green_thr_credit_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGuaranteemethodcd() {
        return guaranteemethodcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.guaranteeMethodCd
     *
     * @param guaranteemethodcd the value for send_green_thr_credit_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGuaranteemethodcd(String guaranteemethodcd) {
        this.guaranteemethodcd = guaranteemethodcd == null ? null : guaranteemethodcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.marginLevel
     *
     * @return the value of send_green_thr_credit_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getMarginlevel() {
        return marginlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.marginLevel
     *
     * @param marginlevel the value for send_green_thr_credit_info.marginLevel
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setMarginlevel(String marginlevel) {
        this.marginlevel = marginlevel == null ? null : marginlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.greenDecidedDate
     *
     * @return the value of send_green_thr_credit_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGreendecideddate() {
        return greendecideddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.greenDecidedDate
     *
     * @param greendecideddate the value for send_green_thr_credit_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGreendecideddate(String greendecideddate) {
        this.greendecideddate = greendecideddate == null ? null : greendecideddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.cbrcGreenClass
     *
     * @return the value of send_green_thr_credit_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCbrcgreenclass() {
        return cbrcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.cbrcGreenClass
     *
     * @param cbrcgreenclass the value for send_green_thr_credit_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCbrcgreenclass(String cbrcgreenclass) {
        this.cbrcgreenclass = cbrcgreenclass == null ? null : cbrcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.isEnvironmentalInterest
     *
     * @return the value of send_green_thr_credit_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIsenvironmentalinterest() {
        return isenvironmentalinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.isEnvironmentalInterest
     *
     * @param isenvironmentalinterest the value for send_green_thr_credit_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIsenvironmentalinterest(String isenvironmentalinterest) {
        this.isenvironmentalinterest = isenvironmentalinterest == null ? null : isenvironmentalinterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.environmentalInterestCd
     *
     * @return the value of send_green_thr_credit_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnvironmentalinterestcd() {
        return environmentalinterestcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.environmentalInterestCd
     *
     * @param environmentalinterestcd the value for send_green_thr_credit_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnvironmentalinterestcd(String environmentalinterestcd) {
        this.environmentalinterestcd = environmentalinterestcd == null ? null : environmentalinterestcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_credit_info.gdate
     *
     * @return the value of send_green_thr_credit_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_credit_info.gdate
     *
     * @param gdate the value for send_green_thr_credit_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}