package com.hzhx.greenFinance.entity;

public class CustomerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.individualName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String individualname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.documentType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String documenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.documentNumber
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String documentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.gender
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.educationDegree
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String educationdegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.birthday
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String industrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.careerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String careertypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.career
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String career;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String majorbusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.isFarmer
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String isfarmer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_customer_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.organization
     *
     * @return the value of send_green_thr_customer_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.organization
     *
     * @param organization the value for send_green_thr_customer_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.customerNo
     *
     * @return the value of send_green_thr_customer_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.customerNo
     *
     * @param customerno the value for send_green_thr_customer_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.individualName
     *
     * @return the value of send_green_thr_customer_info.individualName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIndividualname() {
        return individualname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.individualName
     *
     * @param individualname the value for send_green_thr_customer_info.individualName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIndividualname(String individualname) {
        this.individualname = individualname == null ? null : individualname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.documentType
     *
     * @return the value of send_green_thr_customer_info.documentType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getDocumenttype() {
        return documenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.documentType
     *
     * @param documenttype the value for send_green_thr_customer_info.documentType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setDocumenttype(String documenttype) {
        this.documenttype = documenttype == null ? null : documenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.documentNumber
     *
     * @return the value of send_green_thr_customer_info.documentNumber
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getDocumentnumber() {
        return documentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.documentNumber
     *
     * @param documentnumber the value for send_green_thr_customer_info.documentNumber
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setDocumentnumber(String documentnumber) {
        this.documentnumber = documentnumber == null ? null : documentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.gender
     *
     * @return the value of send_green_thr_customer_info.gender
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.gender
     *
     * @param gender the value for send_green_thr_customer_info.gender
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.educationDegree
     *
     * @return the value of send_green_thr_customer_info.educationDegree
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEducationdegree() {
        return educationdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.educationDegree
     *
     * @param educationdegree the value for send_green_thr_customer_info.educationDegree
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEducationdegree(String educationdegree) {
        this.educationdegree = educationdegree == null ? null : educationdegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.birthday
     *
     * @return the value of send_green_thr_customer_info.birthday
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.birthday
     *
     * @param birthday the value for send_green_thr_customer_info.birthday
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.industryCd
     *
     * @return the value of send_green_thr_customer_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIndustrycd() {
        return industrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.industryCd
     *
     * @param industrycd the value for send_green_thr_customer_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIndustrycd(String industrycd) {
        this.industrycd = industrycd == null ? null : industrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.careerTypeCd
     *
     * @return the value of send_green_thr_customer_info.careerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCareertypecd() {
        return careertypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.careerTypeCd
     *
     * @param careertypecd the value for send_green_thr_customer_info.careerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCareertypecd(String careertypecd) {
        this.careertypecd = careertypecd == null ? null : careertypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.career
     *
     * @return the value of send_green_thr_customer_info.career
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.career
     *
     * @param career the value for send_green_thr_customer_info.career
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.majorBusiness
     *
     * @return the value of send_green_thr_customer_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getMajorbusiness() {
        return majorbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.majorBusiness
     *
     * @param majorbusiness the value for send_green_thr_customer_info.majorBusiness
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setMajorbusiness(String majorbusiness) {
        this.majorbusiness = majorbusiness == null ? null : majorbusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.isFarmer
     *
     * @return the value of send_green_thr_customer_info.isFarmer
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIsfarmer() {
        return isfarmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.isFarmer
     *
     * @param isfarmer the value for send_green_thr_customer_info.isFarmer
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIsfarmer(String isfarmer) {
        this.isfarmer = isfarmer == null ? null : isfarmer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.businessDate
     *
     * @return the value of send_green_thr_customer_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.businessDate
     *
     * @param businessdate the value for send_green_thr_customer_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_customer_info.gdate
     *
     * @return the value of send_green_thr_customer_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_customer_info.gdate
     *
     * @param gdate the value for send_green_thr_customer_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}