package com.hzhx.greenFinance.entity;

public class LoanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businesstypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String contractno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loanno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.customerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customertypecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanKindCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loankindcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanProduct
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loanproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanPurposeDesc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loanpurposedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loanamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loanbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.timeLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String timelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.loanDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String loandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String expiringdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.overdueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String overduedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.overBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String overbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String guaranteemethodcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.interestRate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String interestrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.repaymentMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String repaymentmethodcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.latestRepayDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String latestrepaydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String fivelevelcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String industrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.isGreen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String isgreen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String greendecideddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String cbrcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String pbcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String localgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String isenvironmentalinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String environmentalinterestcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_loan_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.organization
     *
     * @return the value of send_green_thr_loan_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.organization
     *
     * @param organization the value for send_green_thr_loan_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.businessTypeCd
     *
     * @return the value of send_green_thr_loan_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinesstypecd() {
        return businesstypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.businessTypeCd
     *
     * @param businesstypecd the value for send_green_thr_loan_info.businessTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinesstypecd(String businesstypecd) {
        this.businesstypecd = businesstypecd == null ? null : businesstypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.businessDate
     *
     * @return the value of send_green_thr_loan_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.businessDate
     *
     * @param businessdate the value for send_green_thr_loan_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.contractNo
     *
     * @return the value of send_green_thr_loan_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getContractno() {
        return contractno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.contractNo
     *
     * @param contractno the value for send_green_thr_loan_info.contractNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setContractno(String contractno) {
        this.contractno = contractno == null ? null : contractno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanNo
     *
     * @return the value of send_green_thr_loan_info.loanNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoanno() {
        return loanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanNo
     *
     * @param loanno the value for send_green_thr_loan_info.loanNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoanno(String loanno) {
        this.loanno = loanno == null ? null : loanno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.customerTypeCd
     *
     * @return the value of send_green_thr_loan_info.customerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomertypecd() {
        return customertypecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.customerTypeCd
     *
     * @param customertypecd the value for send_green_thr_loan_info.customerTypeCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomertypecd(String customertypecd) {
        this.customertypecd = customertypecd == null ? null : customertypecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.customerNo
     *
     * @return the value of send_green_thr_loan_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.customerNo
     *
     * @param customerno the value for send_green_thr_loan_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.projectNo
     *
     * @return the value of send_green_thr_loan_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectno() {
        return projectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.projectNo
     *
     * @param projectno the value for send_green_thr_loan_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectno(String projectno) {
        this.projectno = projectno == null ? null : projectno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanKindCd
     *
     * @return the value of send_green_thr_loan_info.loanKindCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoankindcd() {
        return loankindcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanKindCd
     *
     * @param loankindcd the value for send_green_thr_loan_info.loanKindCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoankindcd(String loankindcd) {
        this.loankindcd = loankindcd == null ? null : loankindcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanProduct
     *
     * @return the value of send_green_thr_loan_info.loanProduct
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoanproduct() {
        return loanproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanProduct
     *
     * @param loanproduct the value for send_green_thr_loan_info.loanProduct
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoanproduct(String loanproduct) {
        this.loanproduct = loanproduct == null ? null : loanproduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.businessOrg
     *
     * @return the value of send_green_thr_loan_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessorg() {
        return businessorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.businessOrg
     *
     * @param businessorg the value for send_green_thr_loan_info.businessOrg
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessorg(String businessorg) {
        this.businessorg = businessorg == null ? null : businessorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanPurposeDesc
     *
     * @return the value of send_green_thr_loan_info.loanPurposeDesc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoanpurposedesc() {
        return loanpurposedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanPurposeDesc
     *
     * @param loanpurposedesc the value for send_green_thr_loan_info.loanPurposeDesc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoanpurposedesc(String loanpurposedesc) {
        this.loanpurposedesc = loanpurposedesc == null ? null : loanpurposedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanAmount
     *
     * @return the value of send_green_thr_loan_info.loanAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoanamount() {
        return loanamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanAmount
     *
     * @param loanamount the value for send_green_thr_loan_info.loanAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoanamount(String loanamount) {
        this.loanamount = loanamount == null ? null : loanamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanBalance
     *
     * @return the value of send_green_thr_loan_info.loanBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoanbalance() {
        return loanbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanBalance
     *
     * @param loanbalance the value for send_green_thr_loan_info.loanBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoanbalance(String loanbalance) {
        this.loanbalance = loanbalance == null ? null : loanbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.timeLimit
     *
     * @return the value of send_green_thr_loan_info.timeLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getTimelimit() {
        return timelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.timeLimit
     *
     * @param timelimit the value for send_green_thr_loan_info.timeLimit
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setTimelimit(String timelimit) {
        this.timelimit = timelimit == null ? null : timelimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.loanDate
     *
     * @return the value of send_green_thr_loan_info.loanDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLoandate() {
        return loandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.loanDate
     *
     * @param loandate the value for send_green_thr_loan_info.loanDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLoandate(String loandate) {
        this.loandate = loandate == null ? null : loandate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.expiringDate
     *
     * @return the value of send_green_thr_loan_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getExpiringdate() {
        return expiringdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.expiringDate
     *
     * @param expiringdate the value for send_green_thr_loan_info.expiringDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setExpiringdate(String expiringdate) {
        this.expiringdate = expiringdate == null ? null : expiringdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.overdueDate
     *
     * @return the value of send_green_thr_loan_info.overdueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOverduedate() {
        return overduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.overdueDate
     *
     * @param overduedate the value for send_green_thr_loan_info.overdueDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOverduedate(String overduedate) {
        this.overduedate = overduedate == null ? null : overduedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.overBalance
     *
     * @return the value of send_green_thr_loan_info.overBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOverbalance() {
        return overbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.overBalance
     *
     * @param overbalance the value for send_green_thr_loan_info.overBalance
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOverbalance(String overbalance) {
        this.overbalance = overbalance == null ? null : overbalance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.guaranteeMethodCd
     *
     * @return the value of send_green_thr_loan_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGuaranteemethodcd() {
        return guaranteemethodcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.guaranteeMethodCd
     *
     * @param guaranteemethodcd the value for send_green_thr_loan_info.guaranteeMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGuaranteemethodcd(String guaranteemethodcd) {
        this.guaranteemethodcd = guaranteemethodcd == null ? null : guaranteemethodcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.interestRate
     *
     * @return the value of send_green_thr_loan_info.interestRate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getInterestrate() {
        return interestrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.interestRate
     *
     * @param interestrate the value for send_green_thr_loan_info.interestRate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setInterestrate(String interestrate) {
        this.interestrate = interestrate == null ? null : interestrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.repaymentMethodCd
     *
     * @return the value of send_green_thr_loan_info.repaymentMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getRepaymentmethodcd() {
        return repaymentmethodcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.repaymentMethodCd
     *
     * @param repaymentmethodcd the value for send_green_thr_loan_info.repaymentMethodCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setRepaymentmethodcd(String repaymentmethodcd) {
        this.repaymentmethodcd = repaymentmethodcd == null ? null : repaymentmethodcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.latestRepayDate
     *
     * @return the value of send_green_thr_loan_info.latestRepayDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLatestrepaydate() {
        return latestrepaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.latestRepayDate
     *
     * @param latestrepaydate the value for send_green_thr_loan_info.latestRepayDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLatestrepaydate(String latestrepaydate) {
        this.latestrepaydate = latestrepaydate == null ? null : latestrepaydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.fiveLevelCd
     *
     * @return the value of send_green_thr_loan_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getFivelevelcd() {
        return fivelevelcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.fiveLevelCd
     *
     * @param fivelevelcd the value for send_green_thr_loan_info.fiveLevelCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setFivelevelcd(String fivelevelcd) {
        this.fivelevelcd = fivelevelcd == null ? null : fivelevelcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.industryCd
     *
     * @return the value of send_green_thr_loan_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIndustrycd() {
        return industrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.industryCd
     *
     * @param industrycd the value for send_green_thr_loan_info.industryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIndustrycd(String industrycd) {
        this.industrycd = industrycd == null ? null : industrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.isGreen
     *
     * @return the value of send_green_thr_loan_info.isGreen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIsgreen() {
        return isgreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.isGreen
     *
     * @param isgreen the value for send_green_thr_loan_info.isGreen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIsgreen(String isgreen) {
        this.isgreen = isgreen == null ? null : isgreen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.greenDecidedDate
     *
     * @return the value of send_green_thr_loan_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGreendecideddate() {
        return greendecideddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.greenDecidedDate
     *
     * @param greendecideddate the value for send_green_thr_loan_info.greenDecidedDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGreendecideddate(String greendecideddate) {
        this.greendecideddate = greendecideddate == null ? null : greendecideddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.cbrcGreenClass
     *
     * @return the value of send_green_thr_loan_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCbrcgreenclass() {
        return cbrcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.cbrcGreenClass
     *
     * @param cbrcgreenclass the value for send_green_thr_loan_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCbrcgreenclass(String cbrcgreenclass) {
        this.cbrcgreenclass = cbrcgreenclass == null ? null : cbrcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.pbcGreenClass
     *
     * @return the value of send_green_thr_loan_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPbcgreenclass() {
        return pbcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.pbcGreenClass
     *
     * @param pbcgreenclass the value for send_green_thr_loan_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPbcgreenclass(String pbcgreenclass) {
        this.pbcgreenclass = pbcgreenclass == null ? null : pbcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.localGreenClass
     *
     * @return the value of send_green_thr_loan_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLocalgreenclass() {
        return localgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.localGreenClass
     *
     * @param localgreenclass the value for send_green_thr_loan_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLocalgreenclass(String localgreenclass) {
        this.localgreenclass = localgreenclass == null ? null : localgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.isEnvironmentalInterest
     *
     * @return the value of send_green_thr_loan_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getIsenvironmentalinterest() {
        return isenvironmentalinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.isEnvironmentalInterest
     *
     * @param isenvironmentalinterest the value for send_green_thr_loan_info.isEnvironmentalInterest
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setIsenvironmentalinterest(String isenvironmentalinterest) {
        this.isenvironmentalinterest = isenvironmentalinterest == null ? null : isenvironmentalinterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.environmentalInterestCd
     *
     * @return the value of send_green_thr_loan_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnvironmentalinterestcd() {
        return environmentalinterestcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.environmentalInterestCd
     *
     * @param environmentalinterestcd the value for send_green_thr_loan_info.environmentalInterestCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnvironmentalinterestcd(String environmentalinterestcd) {
        this.environmentalinterestcd = environmentalinterestcd == null ? null : environmentalinterestcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_loan_info.gdate
     *
     * @return the value of send_green_thr_loan_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_loan_info.gdate
     *
     * @param gdate the value for send_green_thr_loan_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}