package com.hzhx.greenFinance.entity;

public class ProjectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectCode
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectIndustryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectindustrycd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.totalInvestAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String totalinvestamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.capitalSourceCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String capitalsourcecd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectLocationCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectlocationcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectAddress
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.projectContent
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String projectcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String cbrcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String pbcgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String localgreenclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.energy
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String energy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.co2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String co2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.cod
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String cod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.nh
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String nh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.so2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String so2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.nox
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String nox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.h2o
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String h2o;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.fineParticle
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String fineparticle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.voc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String voc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.nitrogen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String nitrogen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.phosphorus
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String phosphorus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.sceneType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String scenetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.elementType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String elementtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.environElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String environelement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.publicEnvironElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String publicenvironelement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String businessdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column send_green_thr_project_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    private String gdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.organization
     *
     * @return the value of send_green_thr_project_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.organization
     *
     * @param organization the value for send_green_thr_project_info.organization
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectNo
     *
     * @return the value of send_green_thr_project_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectno() {
        return projectno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectNo
     *
     * @param projectno the value for send_green_thr_project_info.projectNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectno(String projectno) {
        this.projectno = projectno == null ? null : projectno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectCode
     *
     * @return the value of send_green_thr_project_info.projectCode
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectcode() {
        return projectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectCode
     *
     * @param projectcode the value for send_green_thr_project_info.projectCode
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode == null ? null : projectcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectName
     *
     * @return the value of send_green_thr_project_info.projectName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectName
     *
     * @param projectname the value for send_green_thr_project_info.projectName
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.customerNo
     *
     * @return the value of send_green_thr_project_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.customerNo
     *
     * @param customerno the value for send_green_thr_project_info.customerNo
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectIndustryCd
     *
     * @return the value of send_green_thr_project_info.projectIndustryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectindustrycd() {
        return projectindustrycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectIndustryCd
     *
     * @param projectindustrycd the value for send_green_thr_project_info.projectIndustryCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectindustrycd(String projectindustrycd) {
        this.projectindustrycd = projectindustrycd == null ? null : projectindustrycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.totalInvestAmount
     *
     * @return the value of send_green_thr_project_info.totalInvestAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getTotalinvestamount() {
        return totalinvestamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.totalInvestAmount
     *
     * @param totalinvestamount the value for send_green_thr_project_info.totalInvestAmount
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setTotalinvestamount(String totalinvestamount) {
        this.totalinvestamount = totalinvestamount == null ? null : totalinvestamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.capitalSourceCd
     *
     * @return the value of send_green_thr_project_info.capitalSourceCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCapitalsourcecd() {
        return capitalsourcecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.capitalSourceCd
     *
     * @param capitalsourcecd the value for send_green_thr_project_info.capitalSourceCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCapitalsourcecd(String capitalsourcecd) {
        this.capitalsourcecd = capitalsourcecd == null ? null : capitalsourcecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectLocationCd
     *
     * @return the value of send_green_thr_project_info.projectLocationCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectlocationcd() {
        return projectlocationcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectLocationCd
     *
     * @param projectlocationcd the value for send_green_thr_project_info.projectLocationCd
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectlocationcd(String projectlocationcd) {
        this.projectlocationcd = projectlocationcd == null ? null : projectlocationcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectAddress
     *
     * @return the value of send_green_thr_project_info.projectAddress
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectaddress() {
        return projectaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectAddress
     *
     * @param projectaddress the value for send_green_thr_project_info.projectAddress
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectaddress(String projectaddress) {
        this.projectaddress = projectaddress == null ? null : projectaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.projectContent
     *
     * @return the value of send_green_thr_project_info.projectContent
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getProjectcontent() {
        return projectcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.projectContent
     *
     * @param projectcontent the value for send_green_thr_project_info.projectContent
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setProjectcontent(String projectcontent) {
        this.projectcontent = projectcontent == null ? null : projectcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.cbrcGreenClass
     *
     * @return the value of send_green_thr_project_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCbrcgreenclass() {
        return cbrcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.cbrcGreenClass
     *
     * @param cbrcgreenclass the value for send_green_thr_project_info.cbrcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCbrcgreenclass(String cbrcgreenclass) {
        this.cbrcgreenclass = cbrcgreenclass == null ? null : cbrcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.pbcGreenClass
     *
     * @return the value of send_green_thr_project_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPbcgreenclass() {
        return pbcgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.pbcGreenClass
     *
     * @param pbcgreenclass the value for send_green_thr_project_info.pbcGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPbcgreenclass(String pbcgreenclass) {
        this.pbcgreenclass = pbcgreenclass == null ? null : pbcgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.localGreenClass
     *
     * @return the value of send_green_thr_project_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getLocalgreenclass() {
        return localgreenclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.localGreenClass
     *
     * @param localgreenclass the value for send_green_thr_project_info.localGreenClass
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setLocalgreenclass(String localgreenclass) {
        this.localgreenclass = localgreenclass == null ? null : localgreenclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.energy
     *
     * @return the value of send_green_thr_project_info.energy
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.energy
     *
     * @param energy the value for send_green_thr_project_info.energy
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnergy(String energy) {
        this.energy = energy == null ? null : energy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.co2
     *
     * @return the value of send_green_thr_project_info.co2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCo2() {
        return co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.co2
     *
     * @param co2 the value for send_green_thr_project_info.co2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCo2(String co2) {
        this.co2 = co2 == null ? null : co2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.cod
     *
     * @return the value of send_green_thr_project_info.cod
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getCod() {
        return cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.cod
     *
     * @param cod the value for send_green_thr_project_info.cod
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setCod(String cod) {
        this.cod = cod == null ? null : cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.nh
     *
     * @return the value of send_green_thr_project_info.nh
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getNh() {
        return nh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.nh
     *
     * @param nh the value for send_green_thr_project_info.nh
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setNh(String nh) {
        this.nh = nh == null ? null : nh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.so2
     *
     * @return the value of send_green_thr_project_info.so2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getSo2() {
        return so2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.so2
     *
     * @param so2 the value for send_green_thr_project_info.so2
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setSo2(String so2) {
        this.so2 = so2 == null ? null : so2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.nox
     *
     * @return the value of send_green_thr_project_info.nox
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getNox() {
        return nox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.nox
     *
     * @param nox the value for send_green_thr_project_info.nox
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setNox(String nox) {
        this.nox = nox == null ? null : nox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.h2o
     *
     * @return the value of send_green_thr_project_info.h2o
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getH2o() {
        return h2o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.h2o
     *
     * @param h2o the value for send_green_thr_project_info.h2o
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setH2o(String h2o) {
        this.h2o = h2o == null ? null : h2o.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.fineParticle
     *
     * @return the value of send_green_thr_project_info.fineParticle
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getFineparticle() {
        return fineparticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.fineParticle
     *
     * @param fineparticle the value for send_green_thr_project_info.fineParticle
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setFineparticle(String fineparticle) {
        this.fineparticle = fineparticle == null ? null : fineparticle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.voc
     *
     * @return the value of send_green_thr_project_info.voc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getVoc() {
        return voc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.voc
     *
     * @param voc the value for send_green_thr_project_info.voc
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setVoc(String voc) {
        this.voc = voc == null ? null : voc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.nitrogen
     *
     * @return the value of send_green_thr_project_info.nitrogen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getNitrogen() {
        return nitrogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.nitrogen
     *
     * @param nitrogen the value for send_green_thr_project_info.nitrogen
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setNitrogen(String nitrogen) {
        this.nitrogen = nitrogen == null ? null : nitrogen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.phosphorus
     *
     * @return the value of send_green_thr_project_info.phosphorus
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPhosphorus() {
        return phosphorus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.phosphorus
     *
     * @param phosphorus the value for send_green_thr_project_info.phosphorus
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPhosphorus(String phosphorus) {
        this.phosphorus = phosphorus == null ? null : phosphorus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.sceneType
     *
     * @return the value of send_green_thr_project_info.sceneType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getScenetype() {
        return scenetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.sceneType
     *
     * @param scenetype the value for send_green_thr_project_info.sceneType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setScenetype(String scenetype) {
        this.scenetype = scenetype == null ? null : scenetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.elementType
     *
     * @return the value of send_green_thr_project_info.elementType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getElementtype() {
        return elementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.elementType
     *
     * @param elementtype the value for send_green_thr_project_info.elementType
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setElementtype(String elementtype) {
        this.elementtype = elementtype == null ? null : elementtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.environElement
     *
     * @return the value of send_green_thr_project_info.environElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getEnvironelement() {
        return environelement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.environElement
     *
     * @param environelement the value for send_green_thr_project_info.environElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setEnvironelement(String environelement) {
        this.environelement = environelement == null ? null : environelement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.publicEnvironElement
     *
     * @return the value of send_green_thr_project_info.publicEnvironElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getPublicenvironelement() {
        return publicenvironelement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.publicEnvironElement
     *
     * @param publicenvironelement the value for send_green_thr_project_info.publicEnvironElement
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setPublicenvironelement(String publicenvironelement) {
        this.publicenvironelement = publicenvironelement == null ? null : publicenvironelement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.businessDate
     *
     * @return the value of send_green_thr_project_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getBusinessdate() {
        return businessdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.businessDate
     *
     * @param businessdate the value for send_green_thr_project_info.businessDate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setBusinessdate(String businessdate) {
        this.businessdate = businessdate == null ? null : businessdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column send_green_thr_project_info.gdate
     *
     * @return the value of send_green_thr_project_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public String getGdate() {
        return gdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column send_green_thr_project_info.gdate
     *
     * @param gdate the value for send_green_thr_project_info.gdate
     *
     * @mbggenerated Wed Nov 25 16:06:05 CST 2020
     */
    public void setGdate(String gdate) {
        this.gdate = gdate == null ? null : gdate.trim();
    }
}